### ISSUE TITLE
How does your method perform on CALVIN ABC-D?

### ISSUE THREAD

**Issue by ygtxr1997** [intuitive-robots/mdt_policy#9]
After using your method to train on CALVIN's task_ABC_D, I got the avg_seq_len~=1.2, where the config was mainly based on config_ABCD_D.yaml. I'm not sure if this is the expected performance.

Although you didn't show the experiments results on CALVIN ABC to D, could you give a rough result on this task?

**Comment by Mark-98** [comment]
I also have same question when i using mdt method to train CALVIN task_ABC_D, Igot the avg_seq_len ~=1.5, where the config was mainly based on config_ABCD_D.yaml.

**Comment by mbreuss** [comment]
Hi, if you make the model bigger I got an average of approx. 1.5 that I reported for the paper here: https://arxiv.org/abs/2408.14368 

However with a few changes its easy to boost performance up to 2.5  using an Ensemble of ResNets. Since that is not part of the official paper i did not add it here. Can you write me an email then I'll share the code for that?

**Comment by Mark-98** [comment]
I had a discussion with a previous author of GR-1, and you suggested that the performance drop in CALVIN ABC -> D might be due to the model size. However, even after scaling up the model, there doesn’t seem to be a significant improvement from your above answer.

One difference between MDT and GR-1 Chunk is that MDT predicts 10 actions and uses all 10, whereas GR-1 Chunk predicts 10 actions but only uses 1.

In the ABC -> D scenario, I assume that the generalization ability might be slightly weaker because the model wasn’t exposed to D during training. So, I tried using your released D -> D MDT-V model, but only changed the multi-step prediction to 1 and 4 steps. Still, the performance on D showed a drop.

I’m curious as to why this happens. Could you share any insights or findings from your research or papers that might help explain this?

Also, if possible, I would appreciate it if you could share the related code with me at yong5835@gmail.com.

Thank you so much!

**Comment by ygtxr1997** [comment]
> Hi, if you make the model bigger I got an average of approx. 1.5 that I reported for the paper here: https://arxiv.org/abs/2408.14368
> 
> However with a few changes its easy to boost performance up to 2.5 using an Ensemble of ResNets. Since that is not part of the official paper i did not add it here. Can you write me an email then I'll share the code for that?

I would like to appreciate your code to see what kinds of changes could further boost the performance to 2.5 using Ensemble ResNets. My email address is: gavinyuan97@gmail.com . Thank you for your sharing!

Besides, does the reported 1.5 avg_seq_len result use the `Proprio` data in CALVIN? Becasue in your mentioned [paper](https://arxiv.org/pdf/2408.14368), your method is marked with `Use Play Data`, which I'm not sure if it means you used not only RGB images but also `Proprio` data.

**Comment by mbreuss** [comment]
@ygtxr1997 Play data refers to the unannotated part. of the CALVIN dataset that makes up 70% of the full CALVIN dataset. I do not use proprio as input. I tired it a bit but it did not help performance and in contrast reduced it. I am still confused why so many papers can use it well without their methods sacrificing performance. If you find the trick to that, let me know. 

One very interesting idea of GR-MG for Calvin is the usage of a special delta end-effector action sapce, which was discussed in on of their issues, maybe that also helps for generalization.

The problem of MDT for the ABC performance is Voltron. While its very strong in the in-domain setting of ABCD and D, it has very bad performance of ABC somehow. I am not sure what the issue is to be honest. By switching to other image encoders I got better performance. 

I am on vacation this week, so ill try to do it next week.

**Comment by ygtxr1997** [comment]
Your shared ideas are very helpful! I'll also do some related experiments following these ideas.

Have a nice week!

**Comment by praveena2j** [comment]
Hi @mbreuss thanks for sharing the code for your interesting work, I also tried your code on ABC-D and got low performance around 1.3, you have mentioned hat the problem could be Voltron and changing to other image encoders, you got better results. Can you share more details on what other image encoders you tried and how much performance boost you achieved, that would be really helpful, once again thank you your work
